spring:
  application:
    name: service

server:
  port: 8080

eureka:
  instance:
#    以IP作为EUREKA注册的hostName
#    hostname: service1
    prefer-ip-address: true
    non-secure-port: ${server.port}
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/